from config import (
    ADMIN_IDS,
    ADMIN_PASSWORD,
    ADMIN_USERNAME,
    BOT_TOKEN,
    DATABASE_URL,
    DELIVERY_FREE_DISTANCE_KM,
    DELIVERY_PRICE_PER_KM,
    ORDER_GROUP_ID,
    SECRET_KEY,
    SHOP_LAT,
    SHOP_LNG,
    WEBAPP_URL,
)
